"""
SciAgents-inspired Scientist Agent

Generates hypotheses using the 7-point SciAgents framework.
"""
import json
from typing import AsyncIterator

from .base_agent import BaseAgent, AgentResult
from .scientist_input import prepare_scientist_input
from .confidence import calculate_scientist_confidence


class ScientistAgent(BaseAgent):
    """Scientist Agent - Hypothesis Generation from Knowledge Graph."""
    name = "scientist"

    async def run(self, state: dict) -> AgentResult:
        """Main scientist execution."""
        planner_output = state.get("planner_output", {})
        if not planner_output:
            return self._result({"error": "No planner output provided"}, confidence=0.0)

        subgraph = planner_output.get("subgraph", {})
        scientist_input = prepare_scientist_input(
            subgraph=subgraph,
            natural_language=planner_output.get("natural_language_context", ""),
            kg_metadata=planner_output.get("kg_metadata", {}),
            enriched=planner_output.get("enriched_analysis", {}),
            user_query=state.get("user_query", "")
        )

        try:
            response = await self._ask("scientist", scientist_input)
            hypothesis = self._validate_and_enhance(response, subgraph)
        except Exception as e:
            return self._result({"error": f"Hypothesis generation failed: {e}"}, confidence=0.0)

        return self._result(hypothesis, confidence=calculate_scientist_confidence(hypothesis, subgraph))

    async def run_stream(self, state: dict) -> AsyncIterator[str]:
        """Stream hypothesis generation in real-time."""
        planner_output = state.get("planner_output", {})
        if not planner_output:
            yield json.dumps({"error": "No planner output provided"})
            return

        subgraph = planner_output.get("subgraph", {})
        scientist_input = prepare_scientist_input(
            subgraph=subgraph,
            natural_language=planner_output.get("natural_language_context", ""),
            kg_metadata=planner_output.get("kg_metadata", {}),
            enriched=planner_output.get("enriched_analysis", {}),
            user_query=state.get("user_query", "")
        )

        async for chunk in self._ask_stream("scientist", scientist_input):
            yield chunk

    def _validate_and_enhance(self, response: dict, subgraph: dict) -> dict:
        """Validate LLM response and enhance with additional metadata."""
        required = ["hypothesis", "expected_outcomes", "mechanisms",
                    "design_principles", "comparison", "novelty"]
        for field in required:
            if field not in response:
                response[field] = {"note": "Field not generated by LLM"}

        if "citations" not in response:
            response["citations"] = {
                "graph_nodes_used": [n.get("id") for n in subgraph.get("nodes", [])],
                "graph_edges_used": [e.get("id") for e in subgraph.get("edges", []) if e.get("id")],
                "auto_generated": True
            }

        response["_metadata"] = {
            "agent": "scientist", "framework": "SciAgents-7-point",
            "subgraph_nodes": len(subgraph.get("nodes", [])),
            "subgraph_edges": len(subgraph.get("edges", []))
        }
        return response
